spring.application.name=taskmanager
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.datasource.url=jdbc:postgresql://192.168.100.84:5432/testdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=I8ENhF5Z4jdmrb7f8Dl91JoqD9DVJH5tlcavpU2Uoef/DmtsJroxzsbM58gbVhYf
jwt.expiration=360000

spring.security.user.name=admin
spring.security.user.password=secret123

